# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 663f626541237fdf060aadad700a02787a29e18bd1c21308c0f8c7eb4332a428d85cccbc1b4071f253a3015714f3dee40367db54c473419e70f67a45a245eee3

test:
  secret_key_base: d105db129abb27ee16bb89cb43465995d8362815cd760c33e41d4fbce7e787877265bd81359fb33f767de6ba04bfb31ef33e514258af987c7c9e52e47805ed60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
